/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parameter-governance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Parameter Governance */
        get: operations["parameter_governance_parameter_governance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Simulate */
        post: operations["simulate_simulate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Evaluate */
        post: operations["evaluate_evaluate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calibrate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Calibrate Endpoint */
        post: operations["calibrate_endpoint_calibrate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sensitivity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sensitivity Endpoint */
        post: operations["sensitivity_endpoint_sensitivity_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/compare-interventions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compare Endpoint */
        post: operations["compare_endpoint_compare_interventions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CalibrationRequest */
        CalibrationRequest: {
            scenario?: components["schemas"]["ModelScenario"];
            /** Observations */
            observations: components["schemas"]["ObservationPoint"][];
            /** Fit Parameters */
            fit_parameters?: string[] | null;
            /** Initial Guess */
            initial_guess?: {
                [key: string]: number;
            } | null;
            /**
             * Max Nfev
             * @default 300
             */
            max_nfev: number;
        };
        /** CalibrationResponse */
        CalibrationResponse: {
            /** Fit Parameters */
            fit_parameters: string[];
            /** Fitted Parameters */
            fitted_parameters: {
                [key: string]: number;
            };
            /** Rmse */
            rmse: number;
            /** Mae */
            mae: number;
            /** Success */
            success: boolean;
            /** Message */
            message: string;
            /** Nfev */
            nfev: number;
            parameter_governance: components["schemas"]["ParameterGovernanceResponse"];
        };
        /** CompareRequest */
        CompareRequest: {
            baseline?: components["schemas"]["ModelScenario"];
            /** Interventions */
            interventions: components["schemas"]["InterventionCase"][];
            /**
             * Mode
             * @default deterministic
             * @enum {string}
             */
            mode: "deterministic" | "stochastic";
            /** Seed */
            seed?: number | null;
            /**
             * Runs
             * @default 1
             */
            runs: number;
        };
        /** CompareResponse */
        CompareResponse: {
            baseline: components["schemas"]["SimulationSummary"];
            /** Interventions */
            interventions: components["schemas"]["InterventionDelta"][];
        };
        /** DistributionStats */
        DistributionStats: {
            /** Omega Mean */
            omega_mean: number;
            /** Omega Std */
            omega_std: number;
            /** Omega Min */
            omega_min: number;
            /** Omega Max */
            omega_max: number;
            /** Probability Mean */
            probability_mean: number;
            /** Probability Std */
            probability_std: number;
            /** Probability Min */
            probability_min: number;
            /** Probability Max */
            probability_max: number;
        };
        /** EvaluateRequest */
        EvaluateRequest: {
            /** Omega */
            omega: number;
            /**
             * Theta
             * @default 40
             */
            theta: number;
            /**
             * Extrinsic X
             * @default 0
             */
            extrinsic_x: number;
            /**
             * Probability Gain
             * @default 6
             */
            probability_gain: number;
        };
        /** EvaluateResponse */
        EvaluateResponse: {
            /** Probability */
            probability: number;
        };
        /** FeedbackStep */
        FeedbackStep: {
            /** Iteration */
            iteration: number;
            /** Psi */
            psi: number;
            /** Omega */
            omega: number;
            /** Probability */
            probability: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InterventionCase */
        InterventionCase: {
            /** Name */
            name: string;
            scenario: components["schemas"]["ModelScenario"];
        };
        /** InterventionDelta */
        InterventionDelta: {
            /** Name */
            name: string;
            /** Omega */
            omega: number;
            /** Probability */
            probability: number;
            /** Delta Omega */
            delta_omega: number;
            /** Delta Probability */
            delta_probability: number;
        };
        /** ModelScenario */
        ModelScenario: {
            /**
             * T Start
             * @default 0
             */
            t_start: number;
            /**
             * T F
             * @default 1
             */
            t_f: number;
            /**
             * N Steps
             * @default 240
             */
            n_steps: number;
            /**
             * A
             * @default 2.4
             */
            A: number;
            /**
             * Alpha
             * @default 2.8
             */
            alpha: number;
            /**
             * Beta
             * @default 0.15
             */
            beta: number;
            /**
             * Lambda0
             * @default 0.6
             */
            lambda0: number;
            /**
             * Gamma
             * @default 0.2
             */
            gamma: number;
            /**
             * C
             * @default 4.2
             */
            C: number;
            /**
             * Iota
             * @default 0.8
             */
            iota: number;
            /**
             * R S
             * @default 1
             */
            R_s: number;
            /**
             * R F
             * @default 1
             */
            R_f: number;
            /**
             * Rho
             * @default 0.6
             */
            rho: number;
            /**
             * Delta
             * @default 0.05
             */
            delta: number;
            /**
             * X P0
             * @default 8
             */
            X_p0: number;
            /**
             * Sigma Task
             * @default 0.6
             */
            sigma_task: number;
            /**
             * D0
             * @default 1
             */
            D0: number;
            /**
             * N D
             * @default 3
             */
            N_d: number;
            /**
             * Eta
             * @default 0.3
             */
            eta: number;
            /**
             * Distraction Impact
             * @default 0.25
             */
            distraction_impact: number;
            /**
             * Sigma0
             * @default 0.1
             */
            sigma0: number;
            /**
             * Sigma1
             * @default 0.03
             */
            sigma1: number;
            /**
             * Theta
             * @default 40
             */
            theta: number;
            /**
             * Extrinsic X
             * @default 0
             */
            extrinsic_x: number;
            /**
             * Probability Gain
             * @default 6
             */
            probability_gain: number;
            /**
             * Psi Gain
             * @default 8
             */
            psi_gain: number;
            /**
             * Psi Midpoint
             * @default 0.5
             */
            psi_midpoint: number;
            /**
             * Feedback Iterations
             * @default 8
             */
            feedback_iterations: number;
            /**
             * Feedback Tolerance
             * @default 0.0001
             */
            feedback_tolerance: number;
        };
        /** ObservationPoint */
        ObservationPoint: {
            /** Time */
            time: number;
            /** Output */
            output: number;
        };
        /** ParameterGovernanceResponse */
        ParameterGovernanceResponse: {
            /** Scenario Inputs */
            scenario_inputs: string[];
            /** Fitted Parameters */
            fitted_parameters: string[];
            /** Notes */
            notes: string;
        };
        /** SensitivityItem */
        SensitivityItem: {
            /** Parameter */
            parameter: string;
            /** Base Value */
            base_value: number;
            /** Plus Value */
            plus_value: number;
            /** Minus Value */
            minus_value: number;
            /** Metric Plus */
            metric_plus: number;
            /** Metric Minus */
            metric_minus: number;
            /** Gradient */
            gradient: number;
            /** Normalized Impact */
            normalized_impact: number;
        };
        /** SensitivityRequest */
        SensitivityRequest: {
            scenario?: components["schemas"]["ModelScenario"];
            /** Parameters */
            parameters?: string[] | null;
            /**
             * Relative Step
             * @default 0.05
             */
            relative_step: number;
            /**
             * Target
             * @default probability
             * @enum {string}
             */
            target: "omega" | "probability";
        };
        /** SensitivityResponse */
        SensitivityResponse: {
            /**
             * Target
             * @enum {string}
             */
            target: "omega" | "probability";
            /** Base Metric */
            base_metric: number;
            /** Items */
            items: components["schemas"]["SensitivityItem"][];
        };
        /** SimulateRequest */
        SimulateRequest: {
            scenario?: components["schemas"]["ModelScenario"];
            /**
             * Mode
             * @default deterministic
             * @enum {string}
             */
            mode: "deterministic" | "stochastic";
            /** Seed */
            seed?: number | null;
            /**
             * Runs
             * @default 1
             */
            runs: number;
        };
        /** SimulationResponse */
        SimulationResponse: {
            summary: components["schemas"]["SimulationSummary"];
            /** Trajectory */
            trajectory: components["schemas"]["TrajectoryPoint"][];
            /** Feedback */
            feedback: components["schemas"]["FeedbackStep"][];
            distribution?: components["schemas"]["DistributionStats"] | null;
        };
        /** SimulationSummary */
        SimulationSummary: {
            /** Omega */
            omega: number;
            /** Probability */
            probability: number;
            /** Psi */
            psi: number;
            /** Phi */
            phi: number;
            /** Lambda C */
            lambda_c: number;
            /** Peak Output */
            peak_output: number;
            /** Peak Time */
            peak_time: number;
            /**
             * Mode
             * @enum {string}
             */
            mode: "deterministic" | "stochastic";
            /** Runs */
            runs: number;
        };
        /** TrajectoryPoint */
        TrajectoryPoint: {
            /** Time */
            time: number;
            /** Stress */
            stress: number;
            /** Focus */
            focus: number;
            /** Distraction */
            distraction: number;
            /** Output */
            output: number;
            /** Terminal Gate */
            terminal_gate: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    parameter_governance_parameter_governance_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParameterGovernanceResponse"];
                };
            };
        };
    };
    simulate_simulate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evaluate_evaluate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvaluateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    calibrate_endpoint_calibrate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CalibrationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalibrationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sensitivity_endpoint_sensitivity_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SensitivityRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SensitivityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_endpoint_compare_interventions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompareRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompareResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
